### ISSUE TITLE
More particle/noise disables (Feature)

### ISSUE THREAD

**Issue by AByakugans** [Core-Quest/MoreByCore#1]
Hello,
Can you also add option to disable global particles? Small (dot-like) particles floating around the map? These options:

Disable global (world) particle haze
Disable Camera Noise

From this PC modes?

https://github.com/kinsi55/BeatSaber_Tweaks55
or this
https://github.com/Shadnix-was-taken/BeatSaber-ParticleOverdrive

Thank you!

**Comment by Core-Quest** [comment]
I will look into this!, Mind telling me more about Camera Noise I'm not familiar with it.

**Comment by AByakugans** [comment]
It's the distortion efect when you cut the cubes... maybe it is in PC version only. 
The global/world particles removal is more important its even in the menus...

**Comment by Core-Quest** [comment]
I do not believe this is a quest thing.

**Comment by AByakugans** [comment]
I believe so too ... So only the white particles/haze floating all around if could be disabled it would be perfect :-)

**Comment by Core-Quest** [comment]
Ill look into it!

**Comment by Core-Quest** [comment]
Hi, someone already took this idea you may download there mod!
