### ISSUE TITLE
[Feature] Vibration Intensity Controls

### ISSUE THREAD

**Issue by Koreami** [Core-Quest/MoreByCore#2]
Hello, I would like to request, (if possible), a feature that allows you to control the vibration intensities of when the sabers hit different kinds of notes/objects.  (Walls, chains, arcs, notes, etc.)
I feel that it would be nice to be able to fine-tune the vibration intensity of different notes/objects, especially with arcs.

I believe there was a past quest mod on this but I don't remember what the name of the mod was.

+Mini-Requests:
- Slider for vibration intensity control (like JD Fixer)

- Fine tuning button to fine tune vibrations (+0.1, -0.1 or +1, -1)

- Be able to toggle which notes/objects you want to have the vibrations changed.

- Of course if this makes the game prone to crashing/be more unstable don't add it, or even make it a separate mod if you wish to do so.

- Don't add an April Fools update making everything vibrate like crazy >:(

- Potentially don't allow levels of vibration that might break your controller

**Comment by Core-Quest** [comment]
Hi Koreami, Thanks for suggesting this. If I were to add this it would most likely make the game break! I will think about making a seperate mod for this request!

If you have any questions or request feel free to reach out here or my discord: Core#9944


- Core

**Comment by Core-Quest** [comment]
This is also already a thing called rumble mod
