### ISSUE TITLE
Beat Saber Crashes

### ISSUE THREAD

**Issue by BSmod** [Core-Quest/MoreByCore#4]
**Describe the bug**
The game crashes when you open up the pause menu.

**To Reproduce**
Open up the pause menu in a Beat Saber song and the game crashes.

**Expected behavior**
Beat Saber crashes.

**Comment by Core-Quest** [comment]
Hi, Please put a log here and ill take a look if you dont know how to get a mod ask in bsmg-quest-help!

**Comment by oli-ctrl** [comment]
this is most likely an incompatibility between mods try disabling all other mods and see if it still happens
